# Note
<font color=red>

**Respected LU Team,**

**Please reconsider this question as in previous submission I forgot to remove repeated indices.**

**Thank You**

**11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [5]:
import numpy as np 
Z = np.random.randn(10,1)#creates a random vector of given order
print("The original vector is:")
print(Z)
I=np.random.randint(0,len(Z),4)#generates 4 random integers in a specified range,used as index values
J=np.unique(I,axis=0)#removes the duplicate values
print("The Index values are:")
print(J)
print("Final vector after adding 1 to corresponding elements at the specified indices:")
np.add.at(Z,I,1)#Adds 1 to the elements in given vector (Z) at the specified index values(I)
print(Z)

The original vector is:
[[ 1.85377581]
 [-1.36665788]
 [ 0.0585424 ]
 [-0.81152421]
 [-1.5565249 ]
 [-0.07062215]
 [ 0.40337431]
 [-0.81165065]
 [ 1.71072681]
 [-1.64002547]]
The Index values are:
[3 5 7 8]
Final vector after adding 1 to corresponding elements at the specified indices:
[[ 1.85377581]
 [-1.36665788]
 [ 0.0585424 ]
 [ 0.18847579]
 [-1.5565249 ]
 [ 0.92937785]
 [ 0.40337431]
 [ 0.18834935]
 [ 2.71072681]
 [-1.64002547]]
